// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: server.proto

package gnetcli

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceOperation int32

const (
	TraceOperation_Operation_notset  TraceOperation = 0
	TraceOperation_Operation_unknown TraceOperation = 1
	TraceOperation_Operation_write   TraceOperation = 2
	TraceOperation_Operation_read    TraceOperation = 3
)

// Enum value maps for TraceOperation.
var (
	TraceOperation_name = map[int32]string{
		0: "Operation_notset",
		1: "Operation_unknown",
		2: "Operation_write",
		3: "Operation_read",
	}
	TraceOperation_value = map[string]int32{
		"Operation_notset":  0,
		"Operation_unknown": 1,
		"Operation_write":   2,
		"Operation_read":    3,
	}
)

func (x TraceOperation) Enum() *TraceOperation {
	p := new(TraceOperation)
	*p = x
	return p
}

func (x TraceOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (TraceOperation) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x TraceOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceOperation.Descriptor instead.
func (TraceOperation) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type DeviceResultStatus int32

const (
	DeviceResultStatus_Device_notset DeviceResultStatus = 0
	DeviceResultStatus_Device_ok     DeviceResultStatus = 1
	DeviceResultStatus_Device_error  DeviceResultStatus = 2
)

// Enum value maps for DeviceResultStatus.
var (
	DeviceResultStatus_name = map[int32]string{
		0: "Device_notset",
		1: "Device_ok",
		2: "Device_error",
	}
	DeviceResultStatus_value = map[string]int32{
		"Device_notset": 0,
		"Device_ok":     1,
		"Device_error":  2,
	}
)

func (x DeviceResultStatus) Enum() *DeviceResultStatus {
	p := new(DeviceResultStatus)
	*p = x
	return p
}

func (x DeviceResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (DeviceResultStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x DeviceResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceResultStatus.Descriptor instead.
func (DeviceResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

type StreamerType int32

const (
	StreamerType_StreamerType_ssh    StreamerType = 0
	StreamerType_StreamerType_telnet StreamerType = 1
)

// Enum value maps for StreamerType.
var (
	StreamerType_name = map[int32]string{
		0: "StreamerType_ssh",
		1: "StreamerType_telnet",
	}
	StreamerType_value = map[string]int32{
		"StreamerType_ssh":    0,
		"StreamerType_telnet": 1,
	}
)

func (x StreamerType) Enum() *StreamerType {
	p := new(StreamerType)
	*p = x
	return p
}

func (x StreamerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamerType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (StreamerType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x StreamerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamerType.Descriptor instead.
func (StreamerType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

type FileStatus int32

const (
	FileStatus_FileStatus_notset    FileStatus = 0
	FileStatus_FileStatus_ok        FileStatus = 1
	FileStatus_FileStatus_error     FileStatus = 2
	FileStatus_FileStatus_not_found FileStatus = 3
	FileStatus_FileStatus_is_dir    FileStatus = 4
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FileStatus_notset",
		1: "FileStatus_ok",
		2: "FileStatus_error",
		3: "FileStatus_not_found",
		4: "FileStatus_is_dir",
	}
	FileStatus_value = map[string]int32{
		"FileStatus_notset":    0,
		"FileStatus_ok":        1,
		"FileStatus_error":     2,
		"FileStatus_not_found": 3,
		"FileStatus_is_dir":    4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[3].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[3]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

type QA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	NotSendNl     bool                   `protobuf:"varint,3,opt,name=not_send_nl,json=notSendNl,proto3" json:"not_send_nl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QA) Reset() {
	*x = QA{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QA) ProtoMessage() {}

func (x *QA) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QA.ProtoReflect.Descriptor instead.
func (*QA) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *QA) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QA) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QA) GetNotSendNl() bool {
	if x != nil {
		return x.NotSendNl
	}
	return false
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CMD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Trace         bool                   `protobuf:"varint,3,opt,name=trace,proto3" json:"trace,omitempty"`
	Qa            []*QA                  `protobuf:"bytes,4,rep,name=qa,proto3" json:"qa,omitempty"`
	ReadTimeout   float64                `protobuf:"fixed64,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	CmdTimeout    float64                `protobuf:"fixed64,6,opt,name=cmd_timeout,json=cmdTimeout,proto3" json:"cmd_timeout,omitempty"`
	StringResult  bool                   `protobuf:"varint,8,opt,name=string_result,json=stringResult,proto3" json:"string_result,omitempty"`
	HostParams    *HostParams            `protobuf:"bytes,9,opt,name=host_params,json=hostParams,proto3" json:"host_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMD) Reset() {
	*x = CMD{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMD) ProtoMessage() {}

func (x *CMD) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMD.ProtoReflect.Descriptor instead.
func (*CMD) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *CMD) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CMD) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *CMD) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *CMD) GetQa() []*QA {
	if x != nil {
		return x.Qa
	}
	return nil
}

func (x *CMD) GetReadTimeout() float64 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *CMD) GetCmdTimeout() float64 {
	if x != nil {
		return x.CmdTimeout
	}
	return 0
}

func (x *CMD) GetStringResult() bool {
	if x != nil {
		return x.StringResult
	}
	return false
}

func (x *CMD) GetHostParams() *HostParams {
	if x != nil {
		return x.HostParams
	}
	return nil
}

type Device struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PromptExpression string                 `protobuf:"bytes,2,opt,name=prompt_expression,json=promptExpression,proto3" json:"prompt_expression,omitempty"`
	ErrorExpression  string                 `protobuf:"bytes,3,opt,name=error_expression,json=errorExpression,proto3" json:"error_expression,omitempty"`
	PagerExpression  string                 `protobuf:"bytes,4,opt,name=pager_expression,json=pagerExpression,proto3" json:"pager_expression,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPromptExpression() string {
	if x != nil {
		return x.PromptExpression
	}
	return ""
}

func (x *Device) GetErrorExpression() string {
	if x != nil {
		return x.ErrorExpression
	}
	return ""
}

func (x *Device) GetPagerExpression() string {
	if x != nil {
		return x.PagerExpression
	}
	return ""
}

type CMDNetconf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Json          bool                   `protobuf:"varint,3,opt,name=json,proto3" json:"json,omitempty"`
	ReadTimeout   float64                `protobuf:"fixed64,4,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"` // read timeout in seconds
	CmdTimeout    float64                `protobuf:"fixed64,5,opt,name=cmd_timeout,json=cmdTimeout,proto3" json:"cmd_timeout,omitempty"`    // command execution timeout in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMDNetconf) Reset() {
	*x = CMDNetconf{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMDNetconf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDNetconf) ProtoMessage() {}

func (x *CMDNetconf) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDNetconf.ProtoReflect.Descriptor instead.
func (*CMDNetconf) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *CMDNetconf) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CMDNetconf) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *CMDNetconf) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *CMDNetconf) GetReadTimeout() float64 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *CMDNetconf) GetCmdTimeout() float64 {
	if x != nil {
		return x.CmdTimeout
	}
	return 0
}

type CMDTraceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     TraceOperation         `protobuf:"varint,1,opt,name=operation,proto3,enum=gnetcli.TraceOperation" json:"operation,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMDTraceItem) Reset() {
	*x = CMDTraceItem{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMDTraceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDTraceItem) ProtoMessage() {}

func (x *CMDTraceItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDTraceItem.ProtoReflect.Descriptor instead.
func (*CMDTraceItem) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *CMDTraceItem) GetOperation() TraceOperation {
	if x != nil {
		return x.Operation
	}
	return TraceOperation_Operation_notset
}

func (x *CMDTraceItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HostParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Credentials   *Credentials           `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	StreamerType  StreamerType           `protobuf:"varint,6,opt,name=streamer_type,json=streamerType,proto3,enum=gnetcli.StreamerType" json:"streamer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostParams) Reset() {
	*x = HostParams{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostParams) ProtoMessage() {}

func (x *HostParams) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostParams.ProtoReflect.Descriptor instead.
func (*HostParams) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *HostParams) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostParams) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *HostParams) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostParams) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HostParams) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostParams) GetStreamerType() StreamerType {
	if x != nil {
		return x.StreamerType
	}
	return StreamerType_StreamerType_ssh
}

type CMDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           []byte                 `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	OutStr        string                 `protobuf:"bytes,2,opt,name=out_str,json=outStr,proto3" json:"out_str,omitempty"`
	Error         []byte                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorStr      string                 `protobuf:"bytes,4,opt,name=error_str,json=errorStr,proto3" json:"error_str,omitempty"`
	Trace         []*CMDTraceItem        `protobuf:"bytes,5,rep,name=trace,proto3" json:"trace,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMDResult) Reset() {
	*x = CMDResult{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDResult) ProtoMessage() {}

func (x *CMDResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDResult.ProtoReflect.Descriptor instead.
func (*CMDResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *CMDResult) GetOut() []byte {
	if x != nil {
		return x.Out
	}
	return nil
}

func (x *CMDResult) GetOutStr() string {
	if x != nil {
		return x.OutStr
	}
	return ""
}

func (x *CMDResult) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CMDResult) GetErrorStr() string {
	if x != nil {
		return x.ErrorStr
	}
	return ""
}

func (x *CMDResult) GetTrace() []*CMDTraceItem {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CMDResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeviceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           DeviceResultStatus     `protobuf:"varint,1,opt,name=res,proto3,enum=gnetcli.DeviceResultStatus" json:"res,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResult) Reset() {
	*x = DeviceResult{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResult) ProtoMessage() {}

func (x *DeviceResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResult.ProtoReflect.Descriptor instead.
func (*DeviceResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceResult) GetRes() DeviceResultStatus {
	if x != nil {
		return x.Res
	}
	return DeviceResultStatus_Device_notset
}

func (x *DeviceResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	HostParams    *HostParams            `protobuf:"bytes,5,opt,name=host_params,json=hostParams,proto3" json:"host_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *FileDownloadRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FileDownloadRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *FileDownloadRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *FileDownloadRequest) GetHostParams() *HostParams {
	if x != nil {
		return x.HostParams
	}
	return nil
}

type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Status        FileStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=gnetcli.FileStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *FileData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileData) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FileStatus_notset
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Files         []*FileData            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	HostParams    *HostParams            `protobuf:"bytes,6,opt,name=host_params,json=hostParams,proto3" json:"host_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *FileUploadRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FileUploadRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *FileUploadRequest) GetFiles() []*FileData {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileUploadRequest) GetHostParams() *HostParams {
	if x != nil {
		return x.HostParams
	}
	return nil
}

type FilesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileData            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesResult) Reset() {
	*x = FilesResult{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesResult) ProtoMessage() {}

func (x *FilesResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesResult.ProtoReflect.Descriptor instead.
func (*FilesResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *FilesResult) GetFiles() []*FileData {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\agnetcli\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"X\n" +
	"\x02QA\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1e\n" +
	"\vnot_send_nl\x18\x03 \x01(\bR\tnotSendNl\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xfd\x01\n" +
	"\x03CMD\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05trace\x18\x03 \x01(\bR\x05trace\x12\x1b\n" +
	"\x02qa\x18\x04 \x03(\v2\v.gnetcli.QAR\x02qa\x12!\n" +
	"\fread_timeout\x18\x05 \x01(\x01R\vreadTimeout\x12\x1f\n" +
	"\vcmd_timeout\x18\x06 \x01(\x01R\n" +
	"cmdTimeout\x12#\n" +
	"\rstring_result\x18\b \x01(\bR\fstringResult\x124\n" +
	"\vhost_params\x18\t \x01(\v2\x13.gnetcli.HostParamsR\n" +
	"hostParams\"\x9f\x01\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11prompt_expression\x18\x02 \x01(\tR\x10promptExpression\x12)\n" +
	"\x10error_expression\x18\x03 \x01(\tR\x0ferrorExpression\x12)\n" +
	"\x10pager_expression\x18\x04 \x01(\tR\x0fpagerExpression\"\x8a\x01\n" +
	"\n" +
	"CMDNetconf\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04json\x18\x03 \x01(\bR\x04json\x12!\n" +
	"\fread_timeout\x18\x04 \x01(\x01R\vreadTimeout\x12\x1f\n" +
	"\vcmd_timeout\x18\x05 \x01(\x01R\n" +
	"cmdTimeout\"Y\n" +
	"\fCMDTraceItem\x125\n" +
	"\toperation\x18\x01 \x01(\x0e2\x17.gnetcli.TraceOperationR\toperation\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xd0\x01\n" +
	"\n" +
	"HostParams\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x126\n" +
	"\vcredentials\x18\x02 \x01(\v2\x14.gnetcli.CredentialsR\vcredentials\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12:\n" +
	"\rstreamer_type\x18\x06 \x01(\x0e2\x15.gnetcli.StreamerTypeR\fstreamerType\"\xae\x01\n" +
	"\tCMDResult\x12\x10\n" +
	"\x03out\x18\x01 \x01(\fR\x03out\x12\x17\n" +
	"\aout_str\x18\x02 \x01(\tR\x06outStr\x12\x14\n" +
	"\x05error\x18\x03 \x01(\fR\x05error\x12\x1b\n" +
	"\terror_str\x18\x04 \x01(\tR\berrorStr\x12+\n" +
	"\x05trace\x18\x05 \x03(\v2\x15.gnetcli.CMDTraceItemR\x05trace\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"S\n" +
	"\fDeviceResult\x12-\n" +
	"\x03res\x18\x01 \x01(\x0e2\x1b.gnetcli.DeviceResultStatusR\x03res\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x13FileDownloadRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x124\n" +
	"\vhost_params\x18\x05 \x01(\v2\x13.gnetcli.HostParamsR\n" +
	"hostParams\"_\n" +
	"\bFileData\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.gnetcli.FileStatusR\x06status\"\x9e\x01\n" +
	"\x11FileUploadRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12'\n" +
	"\x05files\x18\x03 \x03(\v2\x11.gnetcli.FileDataR\x05files\x124\n" +
	"\vhost_params\x18\x06 \x01(\v2\x13.gnetcli.HostParamsR\n" +
	"hostParams\"6\n" +
	"\vFilesResult\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.gnetcli.FileDataR\x05files*f\n" +
	"\x0eTraceOperation\x12\x14\n" +
	"\x10Operation_notset\x10\x00\x12\x15\n" +
	"\x11Operation_unknown\x10\x01\x12\x13\n" +
	"\x0fOperation_write\x10\x02\x12\x12\n" +
	"\x0eOperation_read\x10\x03*H\n" +
	"\x12DeviceResultStatus\x12\x11\n" +
	"\rDevice_notset\x10\x00\x12\r\n" +
	"\tDevice_ok\x10\x01\x12\x10\n" +
	"\fDevice_error\x10\x02*=\n" +
	"\fStreamerType\x12\x14\n" +
	"\x10StreamerType_ssh\x10\x00\x12\x17\n" +
	"\x13StreamerType_telnet\x10\x01*}\n" +
	"\n" +
	"FileStatus\x12\x15\n" +
	"\x11FileStatus_notset\x10\x00\x12\x11\n" +
	"\rFileStatus_ok\x10\x01\x12\x14\n" +
	"\x10FileStatus_error\x10\x02\x12\x18\n" +
	"\x14FileStatus_not_found\x10\x03\x12\x15\n" +
	"\x11FileStatus_is_dir\x10\x042\x8c\x05\n" +
	"\aGnetcli\x12d\n" +
	"\x0fSetupHostParams\x12\x13.gnetcli.HostParams\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/setup_host_params\x12A\n" +
	"\x04Exec\x12\f.gnetcli.CMD\x1a\x12.gnetcli.CMDResult\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/exec\x122\n" +
	"\bExecChat\x12\f.gnetcli.CMD\x1a\x12.gnetcli.CMDResult\"\x00(\x010\x01\x12R\n" +
	"\tAddDevice\x12\x0f.gnetcli.Device\x1a\x15.gnetcli.DeviceResult\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/add_device\x12W\n" +
	"\vExecNetconf\x12\x13.gnetcli.CMDNetconf\x1a\x12.gnetcli.CMDResult\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/exec_netconf\x12@\n" +
	"\x0fExecNetconfChat\x12\x13.gnetcli.CMDNetconf\x1a\x12.gnetcli.CMDResult\"\x00(\x010\x01\x12\\\n" +
	"\bDownload\x12\x1c.gnetcli.FileDownloadRequest\x1a\x14.gnetcli.FilesResult\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/downloads\x12W\n" +
	"\x06Upload\x12\x1a.gnetcli.FileUploadRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/uploadB7Z5github.com/annetutil/gnetcli/pkg/server/proto;gnetclib\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_proto_goTypes = []any{
	(TraceOperation)(0),         // 0: gnetcli.TraceOperation
	(DeviceResultStatus)(0),     // 1: gnetcli.DeviceResultStatus
	(StreamerType)(0),           // 2: gnetcli.StreamerType
	(FileStatus)(0),             // 3: gnetcli.FileStatus
	(*QA)(nil),                  // 4: gnetcli.QA
	(*Credentials)(nil),         // 5: gnetcli.Credentials
	(*CMD)(nil),                 // 6: gnetcli.CMD
	(*Device)(nil),              // 7: gnetcli.Device
	(*CMDNetconf)(nil),          // 8: gnetcli.CMDNetconf
	(*CMDTraceItem)(nil),        // 9: gnetcli.CMDTraceItem
	(*HostParams)(nil),          // 10: gnetcli.HostParams
	(*CMDResult)(nil),           // 11: gnetcli.CMDResult
	(*DeviceResult)(nil),        // 12: gnetcli.DeviceResult
	(*FileDownloadRequest)(nil), // 13: gnetcli.FileDownloadRequest
	(*FileData)(nil),            // 14: gnetcli.FileData
	(*FileUploadRequest)(nil),   // 15: gnetcli.FileUploadRequest
	(*FilesResult)(nil),         // 16: gnetcli.FilesResult
	(*emptypb.Empty)(nil),       // 17: google.protobuf.Empty
}
var file_server_proto_depIdxs = []int32{
	4,  // 0: gnetcli.CMD.qa:type_name -> gnetcli.QA
	10, // 1: gnetcli.CMD.host_params:type_name -> gnetcli.HostParams
	0,  // 2: gnetcli.CMDTraceItem.operation:type_name -> gnetcli.TraceOperation
	5,  // 3: gnetcli.HostParams.credentials:type_name -> gnetcli.Credentials
	2,  // 4: gnetcli.HostParams.streamer_type:type_name -> gnetcli.StreamerType
	9,  // 5: gnetcli.CMDResult.trace:type_name -> gnetcli.CMDTraceItem
	1,  // 6: gnetcli.DeviceResult.res:type_name -> gnetcli.DeviceResultStatus
	10, // 7: gnetcli.FileDownloadRequest.host_params:type_name -> gnetcli.HostParams
	3,  // 8: gnetcli.FileData.status:type_name -> gnetcli.FileStatus
	14, // 9: gnetcli.FileUploadRequest.files:type_name -> gnetcli.FileData
	10, // 10: gnetcli.FileUploadRequest.host_params:type_name -> gnetcli.HostParams
	14, // 11: gnetcli.FilesResult.files:type_name -> gnetcli.FileData
	10, // 12: gnetcli.Gnetcli.SetupHostParams:input_type -> gnetcli.HostParams
	6,  // 13: gnetcli.Gnetcli.Exec:input_type -> gnetcli.CMD
	6,  // 14: gnetcli.Gnetcli.ExecChat:input_type -> gnetcli.CMD
	7,  // 15: gnetcli.Gnetcli.AddDevice:input_type -> gnetcli.Device
	8,  // 16: gnetcli.Gnetcli.ExecNetconf:input_type -> gnetcli.CMDNetconf
	8,  // 17: gnetcli.Gnetcli.ExecNetconfChat:input_type -> gnetcli.CMDNetconf
	13, // 18: gnetcli.Gnetcli.Download:input_type -> gnetcli.FileDownloadRequest
	15, // 19: gnetcli.Gnetcli.Upload:input_type -> gnetcli.FileUploadRequest
	17, // 20: gnetcli.Gnetcli.SetupHostParams:output_type -> google.protobuf.Empty
	11, // 21: gnetcli.Gnetcli.Exec:output_type -> gnetcli.CMDResult
	11, // 22: gnetcli.Gnetcli.ExecChat:output_type -> gnetcli.CMDResult
	12, // 23: gnetcli.Gnetcli.AddDevice:output_type -> gnetcli.DeviceResult
	11, // 24: gnetcli.Gnetcli.ExecNetconf:output_type -> gnetcli.CMDResult
	11, // 25: gnetcli.Gnetcli.ExecNetconfChat:output_type -> gnetcli.CMDResult
	16, // 26: gnetcli.Gnetcli.Download:output_type -> gnetcli.FilesResult
	17, // 27: gnetcli.Gnetcli.Upload:output_type -> google.protobuf.Empty
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
